version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: ${POSTGRES_HOST}
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=${POSTGRES_SYNC}
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${SERVER_DOCKER_PORT}
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT # expose-to-the-world : only-in-the-docker
    container_name: nest-api
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_DOCKER_LISTEN_PORT}
    ports:
      - $PGADMIN_LOCAL_LISTEN_PORT:$PGADMIN_DOCKER_LISTEN_PORT
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data:
